#! /bin/sh

setxkbmap fi &
numlockx &
pgrep -x sxhkd >/dev/null || sxhkd &

bspc config ignore_ewmh_fullscreen true

if [[ $(xrandr -q | grep "DVI.* connected") ]]; then
	xrandr --output eDP --primary --mode 2560x1600 --rotate normal --output DVI-I-2-1 --mode 1920x1080 --rotate right --right-of eDP
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 20

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bash ~/scripts/touchpad_settings.sh

polybar hansubar &
xsetroot -cursor_name left_ptr &
nitrogen --restore
megasync &
sleep 2 && megasync &
xfce-power-manager &
dunst &
nm-applet &
picom
