#! /bin/sh

setxkbmap fi &
numlockx &
pgrep -x sxhkd >/dev/null || sxhkd &
brightnessctl --device='platform::kbd_backlight' set 1 &

bspc config ignore_ewmh_fullscreen true

~/scripts/dual_monitor.sh

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DVI-I-2-1 -d 󱡶

bspc config border_width 1
bspc config window_gap 20

bspc config focused_border_color "#ea9a97"
bspc config active_border_color "#191724"
bspc config normal_border_color "#191724"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

unclutter -idle 3 &
~/scripts/touchpad_settings.sh &
libinput-gestures-setup start &
killall polybar
polybar hansubar &
polybar secondbar &
xsetroot -cursor_name left_ptr &
nitrogen --restore
~/scripts/init_megasync.sh &
xfce-power-manager &
dunst &
nm-applet &
blueman-applet &
picom
