#! /bin/sh

setxkbmap fi &
numlockx &
pgrep -x sxhkd >/dev/null || sxhkd &
brightnessctl --device='platform::kbd_backlight' set 1 &

bspc config ignore_ewmh_fullscreen true

~/scripts/dual_monitor.sh

#bspc wm --reorder-monitors eDP DVI-I-3-2
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
bspc desktop '^10' --layout monocle
xidlehook --not-when-audio --not-when-fullscreen --timer 360 '/home/kristian/scripts/lock.sh' '' &
bspc config border_width 3
bspc config window_gap 20
bspc top_monocle_padding 5
bspc bottom_monocle_padding 5
bspc left_monocle_padding 5
bspc right_monocle_padding 5

bspc config focused_border_color "#babbf1"
bspc config active_border_color "#303446"
bspc config normal_border_color "#303446"

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a qalculate-gtk state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Audacious desktop=^9
bspc rule -a "Proton Mail Bridge" desktop=^10
bspc rule -a thunderbird desktop=^10
bspc rule -a zen-browser desktop=^1
bspc rule -a zoom desktop=^7
bspc rule -a zoom state=floating
bspc rule -a Slack desktop=^8
bspc rule -a "oy-interact-tira-TIRACodersApp" state=floating
bspc rule -a Yad state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Xarchiver state=floating

unclutter -idle 3 &
~/scripts/touchpad_settings.sh &
libinput-gestures-setup start &
killall polybar
polybar hansubar &
polybar secondbar &
xsetroot -cursor_name left_ptr &
nitrogen --restore
eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"
export SSH_AUTH_SOCK
~/scripts/init_megasync.sh &
dunst &
nm-applet &
blueman-applet &
~/scripts/init_mail.sh &
picom
